name: Nairuby
markdown: redcarpet
highlighter: rouge
permalink: /:categories/:year/:month/:title/
relative_permalinks: false

redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables']

sass:
  sass_dir: _sass
  style: :compressed

exclude: ['CNAME', 'Gemfile', 'Rakefile', 'README.md', 'vendor']

nairuby:
  github_url: https://github.com/Nairuby
  gitlab_url: https://gitlab.com/nairuby
  twitter_url: https://twitter.com/NairubyKE
  facebook_url: https://facebook.com/NairubyKE
  google_plus_url: https://plus.google.com/113027199805523831412/posts
